### ISSUE TITLE
bug: billboarding completely broken

### ISSUE THREAD

**Issue by pernydev** [Erkko68/stable_player_display#1]
Hey! I am not sure where to post this issue, but since this is the most updated repo I decided to post it here. When an item display has billboarding enabled, the model goes all over the place.

[output.webm](https://github.com/user-attachments/assets/c7aa3133-5d14-45e9-a7aa-31bcf4b21894)

**Comment by Erkko68** [comment]
Apologies for the delay in addressing this issue, I just saw it today. The current shader is designed to work only with `item_display` transformations, so billboarding functionality is not and won't be supported.

To achieve a model display that faces the camera, you’ll need to adjust the `left_rotation` and `right_rotation` parameters through commands.
